/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ajout_modification;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import modele.QCM;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauAjoutQCM extends JPanel {

    private ArrayList<JTextField> listeChoix;
    private ArrayList<JCheckBox> listeBonnesReponses;
    private SpinnerModel nombreChoix;
    private JTextField nouveauText;
    private JCheckBox nouveauCheck;
    private QCM maQuestion;

    
    public PanneauAjoutQCM(QCM maQuestion) {
        this();
        this.maQuestion=maQuestion;
        modifierQuestion(maQuestion);
    }

    
    public PanneauAjoutQCM() {
        initComponents();
        setBounds(0, 65, 970, 355);
        ajoutQuestion();

    }
    
    public void ajoutQuestion(){
        nombreChoix = new SpinnerNumberModel(2, 2, 5, 1);
        spinnerChoix.setModel(nombreChoix);
        ((DefaultEditor) spinnerChoix.getEditor()).getTextField().setEditable(false);

        listeChoix = new ArrayList<>();
        listeChoix.add(txtChoix1);
        listeChoix.add(txtChoix2);

        listeBonnesReponses = new ArrayList<>();
        listeBonnesReponses.add(checkBox1);
        listeBonnesReponses.add(checkBox2);
    }
    
    private void modifierQuestion(QCM maQuestion1) {
        //ajoutQuestion();
        txtQuestion.setText(maQuestion1.getLaQuestion());
        int nombreCh = maQuestion1.getListeChoix().size();
        spinnerChoix.setValue(nombreCh);
        while (nombreCh !=listeChoix.size())
            ajoutSupprimerChoix(nombreCh);
        for (int i = 0; i<nombreCh; i++) {
            listeChoix.get(i).setText(maQuestion1.getListeChoix().get(i));
            if (maQuestion1.getReponses(i)) {
                listeBonnesReponses.get(i).setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtChoix1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        txtChoix2 = new javax.swing.JTextField();
        spinnerChoix = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        checkBox1 = new javax.swing.JCheckBox();
        checkBox2 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(219, 219, 219));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        setForeground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(980, 505));
        setLayout(null);

        txtChoix1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(txtChoix1);
        txtChoix1.setBounds(40, 100, 850, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Bonne reponse");
        add(jLabel1);
        jLabel1.setBounds(850, 60, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("La question :");
        add(jLabel2);
        jLabel2.setBounds(20, 15, 100, 30);

        txtQuestion.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(txtQuestion);
        txtQuestion.setBounds(130, 15, 830, 31);

        txtChoix2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(txtChoix2);
        txtChoix2.setBounds(40, 150, 850, 31);

        spinnerChoix.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        spinnerChoix.setModel(new javax.swing.SpinnerListModel(new String[] {"empty"}));
        spinnerChoix.setFocusCycleRoot(true);
        spinnerChoix.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerChoixStateChanged(evt);
            }
        });
        add(spinnerChoix);
        spinnerChoix.setBounds(170, 60, 55, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Liste des choix :");
        add(jLabel3);
        jLabel3.setBounds(20, 60, 140, 30);

        checkBox1.setBackground(new java.awt.Color(219, 219, 219));
        add(checkBox1);
        checkBox1.setBounds(920, 100, 29, 29);

        checkBox2.setBackground(new java.awt.Color(219, 219, 219));
        add(checkBox2);
        checkBox2.setBounds(920, 150, 35, 35);
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerChoixStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerChoixStateChanged
        int nombre = (int) spinnerChoix.getValue();
        ajoutSupprimerChoix(nombre);
    }//GEN-LAST:event_spinnerChoixStateChanged

    private void ajoutSupprimerChoix(int nombre) {
       
        //System.out.println(nombre);
        if (nombre > listeChoix.size()) {
            listeChoix.add(nouveauTextField());
            listeBonnesReponses.add(nouveauCheckBox());
        } else if (nombre < listeChoix.size()) {
            remove(listeChoix.get(listeChoix.size() - 1));
            listeChoix.remove(listeChoix.size() - 1);
            remove(listeBonnesReponses.get(listeBonnesReponses.size() - 1));
            listeBonnesReponses.remove(listeBonnesReponses.size() - 1);
        }
        repaint();
    }

    private JTextField nouveauTextField() {
        nouveauText = new JTextField();
        nouveauText.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(nouveauText);
        nouveauText.setBounds(40, 50 + ((listeChoix.size()+1) * 50), 850, 29);
        return nouveauText;
    }

    private JCheckBox nouveauCheckBox() {
        nouveauCheck = new JCheckBox();
        nouveauCheck.setBackground(new java.awt.Color(219, 219, 219));
        add(nouveauCheck);
        nouveauCheck.setBounds(920, 50 + ((listeChoix.size()) * 50), 31, 29);
        return nouveauCheck;
    }

    public ArrayList<JTextField> getListeChoix() {
        return listeChoix;
    }

    public ArrayList<JCheckBox> getListeBonnesReponses() {
        return listeBonnesReponses;
    }

    public JTextField getTxtQuestion() {
        return txtQuestion;
    }

    public void reinitialiser() {
        txtQuestion.setText("");
        for (int i = 0; i < listeChoix.size(); i++) {
            listeChoix.get(i).setText("");
            listeBonnesReponses.get(i).setSelected(false);
        }
    }

    public boolean validerData() {
        if (txtQuestion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La question est obligatoire!",
                    "Saisie de valeurs", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        for (int i = 0; i < listeChoix.size(); i++) {
            if (listeChoix.get(i).getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Veuillez completer tous les champs manquants",
                        "Saisie de valeurs", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        for (int i = 0; i < listeBonnesReponses.size(); i++) {
            if (listeBonnesReponses.get(i).isSelected()) {
                return true;
            }
        }

        JOptionPane.showMessageDialog(null, "Vous devez cocher au moins une bonne réponse",
                "Choix des bonnes reponses", JOptionPane.ERROR_MESSAGE);
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spinnerChoix;
    private javax.swing.JTextField txtChoix1;
    private javax.swing.JTextField txtChoix2;
    private javax.swing.JTextField txtQuestion;
    // End of variables declaration//GEN-END:variables

}
