/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ajout_modification;

import io.ManipFichier;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modele.ImageErreur;
import modele.ListeQuestions;
import utils.GestionImage;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauAjoutQuesImg extends javax.swing.JPanel {

    private File fichierImage;
    private String pathImage;
    private int numQues;
    private ListeQuestions listeQuestion;
    private ImageIcon imageQuestion;
    private Image imageLblQestion;
    private ImageErreur maQuestion;
    Timer minuteur;
    int intervalle;

    public PanneauAjoutQuesImg() {
        initComponents();
    }

    public PanneauAjoutQuesImg(ListeQuestions listeQuestion) {
        this();
        this.listeQuestion = listeQuestion;
        // System.out.println("num ..." + numQues);
        setBounds(0, 65, 970, 355);

        ajoutQuestion();

    }

    public PanneauAjoutQuesImg(ImageErreur maQuestion) {
        this();
        this.maQuestion = maQuestion;
        setBounds(0, 65, 970, 355);

        modifierQuestion();

    }

    // quand on va ajouter une nouvelle question
    private void modifierQuestion() {
        lblImage.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().getResource(maQuestion.getlImage())).getImage(), lblImage.getWidth(), lblImage.getHeight())));
        txtPath.setText(maQuestion.getlImage());
        pathImage = maQuestion.getlImage();
        txtNum.setText(maQuestion.getLigne(0)[0]);
        txtErreur.setText(maQuestion.getLigne(0)[1]);
        txtCorrection.setText(maQuestion.getLigne(0)[2]);
        repaint();
    }

    // // quand on va modifier une question
    private void ajoutQuestion() {
        choisirImage.setDialogTitle("Choisir une image pour la question");
        choisirImage.setApproveButtonText("Choisit");
        choisirImage.setApproveButtonToolTipText("Attache des fichiers");
        choisirImage.setMultiSelectionEnabled(false);

        //ajuster l'image selon les dimenssions de label
        lblImage.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().
                getResource("/images/choisir.jpg")).getImage(), lblImage.getWidth(), lblImage.getHeight())));
        repaint();
    }

    public String getPathImage() {
        return pathImage;
    }

    public int getNumLigneErreur() {
        return Integer.parseInt(txtNum.getText());
    }

    public String getErreur() {
        return txtErreur.getText();
    }

    public String getCorrection() {
        return txtCorrection.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choisirImage = new javax.swing.JFileChooser();
        btnChoisirImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        txtCorrection = new javax.swing.JTextField();
        txtErreur = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        choisirImage.setPreferredSize(new java.awt.Dimension(500, 399));

        setBackground(new java.awt.Color(219, 219, 219));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        setForeground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(980, 505));
        setLayout(null);

        btnChoisirImage.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnChoisirImage.setText("Choisir image");
        btnChoisirImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoisirImageActionPerformed(evt);
            }
        });
        add(btnChoisirImage);
        btnChoisirImage.setBounds(330, 10, 170, 31);

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        add(lblImage);
        lblImage.setBounds(330, 50, 630, 285);

        txtPath.setEditable(false);
        txtPath.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtPath);
        txtPath.setBounds(500, 10, 455, 30);

        txtCorrection.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(txtCorrection);
        txtCorrection.setBounds(135, 260, 185, 31);

        txtErreur.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(txtErreur);
        txtErreur.setBounds(135, 190, 185, 31);

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        add(txtNum);
        txtNum.setBounds(135, 120, 185, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Correction :");
        add(jLabel1);
        jLabel1.setBounds(25, 260, 115, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel4.setText("Détails de l'erreur sur une image");
        add(jLabel4);
        jLabel4.setBounds(10, 60, 310, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Erreur :");
        add(jLabel5);
        jLabel5.setBounds(25, 190, 115, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("N de ligne :");
        add(jLabel6);
        jLabel6.setBounds(25, 120, 115, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoisirImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoisirImageActionPerformed
        int choix = choisirImage.showOpenDialog(null);
        String pathChoix;
        numQues = listeQuestion.nouveauNumQuestion();
       // String pathDestination = "C:/Users/BaDRi/Documents/NetBeansProjects/projet_quiz_java_final/src/images/ImageCinqErreurs/question" + numQues + ".png";
        String pathDestination = (String.valueOf(getClass().getResource("/images/ImageCinqErreurs")+"/question" + numQues + ".png")).substring(5);
       // System.out.println("dest..."+pathDestination);
        File imgDestination = new File(pathDestination);
        if (choix == JFileChooser.APPROVE_OPTION) {

            fichierImage = choisirImage.getSelectedFile();
            pathChoix = fichierImage.getAbsolutePath();
            pathImage = "/images/ImageCinqErreurs/question" + numQues + ".png";
            txtPath.setText(pathImage);

           /* imageQuestion = new ImageIcon(getClass().getResource("/images/choisir.jpg"));
            imageLblQestion = ajusterImage(imageQuestion.getImage(), lblImage.getHeight(), lblImage.getWidth());
            lblImage.setIcon(new ImageIcon(imageLblQestion));*/
   
            try {
                ManipFichier.copierFichier(fichierImage, imgDestination);
                // afficher la nouvelle image
                imageQuestion = new ImageIcon(pathChoix);
                lblImage.setIcon(new ImageIcon(GestionImage.ajusterImage(imageQuestion.getImage(), lblImage.getWidth(), lblImage.getHeight())));
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Oups... erreur de copie, veuillez reessayer !",
                        "Erreur lors de la copie de limage", JOptionPane.ERROR_MESSAGE);
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Erreur lors de l'affichage de l’image,\n"
                        + "mais vous pouvez terminer l’ajout de la question quand même.",
                        "Erreur lors de l'affichage de l'image", JOptionPane.INFORMATION_MESSAGE);
            }
            

            
            //repaint();
        }
    }//GEN-LAST:event_btnChoisirImageActionPerformed

   
    public void reinitialiser() {
        txtPath.setText("");
        txtNum.setText("");
        txtCorrection.setText("");
        txtErreur.setText("");
        lblImage.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().
                getResource("/images/choisir.jpg")).getImage(), lblImage.getWidth(), lblImage.getHeight())));
        pathImage = "";
    }

    public boolean validerData() {
        if (txtPath.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vous devez choisir une image",
                    "Choix de la question", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtNum.getText().equals("") || txtCorrection.getText().equals("") || txtErreur.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez completer les champs manquants !",
                    "Preciser lerreur sur limage", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            int i = Integer.parseInt(txtNum.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer un chiffre pour le numero de ligne!",
                    "Erreur de saisi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoisirImage;
    private javax.swing.JFileChooser choisirImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtCorrection;
    private javax.swing.JTextField txtErreur;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables

}
