/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ajout_modification;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modele.ResultatExecution;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauAjoutQuesRes extends JPanel {

    ResultatExecution maQuestion;
            
    public PanneauAjoutQuesRes() {
        initComponents();
        setBounds(0, 65, 970, 355);
    }

    public PanneauAjoutQuesRes(ResultatExecution maQuestion) {
        this();
        this.maQuestion=maQuestion;
        modifierQuestion(maQuestion);
        repaint();
    }
    
    private void modifierQuestion(ResultatExecution maQuestion) {
        String question, reponse;
        question = maQuestion.getQuestion();
        reponse = maQuestion.getReponse();
        txtAreaQuestion.setText(question);
        txtResultat.setText(reponse);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaQuestion = new javax.swing.JTextArea();
        txtResultat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 219, 219));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        setForeground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(970, 355));
        setLayout(null);

        txtAreaQuestion.setColumns(20);
        txtAreaQuestion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAreaQuestion.setRows(5);
        jScrollPane1.setViewportView(txtAreaQuestion);

        add(jScrollPane1);
        jScrollPane1.setBounds(470, 40, 440, 180);

        txtResultat.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtResultat);
        txtResultat.setBounds(470, 260, 440, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Le resultat d'execution de code ci-dissus :");
        add(jLabel1);
        jLabel1.setBounds(75, 260, 390, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Tapez la question (code Java) :");
        add(jLabel2);
        jLabel2.setBounds(75, 60, 300, 31);
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getTxtAreaQuestion() {
        return txtAreaQuestion;
    }

    public JTextField getTxtResultat() {
        return txtResultat;
    }

    public void reinitialiser() {
        txtAreaQuestion.setText("");
        txtResultat.setText("");
    }

    public boolean validerData() {
        if (txtAreaQuestion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La question est obligatoire! Vauillez taper une partie de code Java",
                    "Saisie de valeurs", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtResultat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le resultat d'execution du code tapé ci-dissus est obligatoire!",
                    "Saisie de valeurs", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaQuestion;
    private javax.swing.JTextField txtResultat;
    // End of variables declaration//GEN-END:variables

}
