/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import utils.GestionImage;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class FenDiagramme extends javax.swing.JFrame {

    /**
     * Creates new form FenDiagramme
     */

    private int compteur;
    private String[] listeImages;
    private String[] listeTitres;

    public FenDiagramme() {
        initComponents();
    }
    
    public FenDiagramme(int nombre) {
        this();
        compteur=nombre;
        listeImages = new String[]{"/images/Diagrammes_uml/Use_Case_Diagram.jpg","/images/Diagrammes_uml/Class_Diagram.jpg"};
        listeTitres = new String[]{"Diagramme de cas d'utilisation","Diagrammes de classe de conception"};
        mettreAjour();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblTitre = new javax.swing.JLabel();
        btnPrecedent = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 845));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);
        jPanel1.add(lblImage);
        lblImage.setBounds(0, 50, 1270, 750);

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lblTitre.setText("Diagramme de cas d'utilisation");
        jPanel1.add(lblTitre);
        lblTitre.setBounds(330, 0, 520, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 0, 1280, 800);

        btnPrecedent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-arrow-left-icon.png"))); // NOI18N
        btnPrecedent.setText("jButton1");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrecedent);
        btnPrecedent.setBounds(0, 320, 96, 96);

        btnSuivant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-arrow-right-icon.png"))); // NOI18N
        btnSuivant.setText("jButton1");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivant);
        btnSuivant.setBounds(1380, 320, 96, 96);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Suivant
    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        compteur++;
        mettreAjour();
    }//GEN-LAST:event_btnSuivantActionPerformed

    //Precedent
    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        compteur--;
        mettreAjour();
    }//GEN-LAST:event_btnPrecedentActionPerformed

    
    private void mettreAjour(){
        if (compteur>= listeImages.length)
            compteur=0;
        else if (compteur < 0)
            compteur=listeImages.length-1;
 
        // charger une image de diagramme
        lblImage.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().getResource(listeImages[compteur])).getImage(),
                lblImage.getWidth(), lblImage.getHeight())));
        
        //Changer le titre de diagramme
        lblTitre.setText(listeTitres[compteur]);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitre;
    // End of variables declaration//GEN-END:variables
}
