/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Font;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextArea;

import modele.ImageErreur;
import modele.QCM;
import modele.ResultatExecution;

import utils.GestionImage;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauParcours extends javax.swing.JPanel {

    private QCM questionQCM;
    private ImageErreur questionImg;
    private ResultatExecution questionResExe;
    
    private JLabel lblQuestion;
    private JLabel[] tabChoix;
    private MouseMotionAdapter passerSouris;
    private MouseAdapter sortirSouris;
    
    private JTextArea txtArea;

    /**
     * Creates new form PanneauTest2
     */
    
    // Constructeur #1 (QCM)
    public PanneauParcours(QCM questionQCM) {
        this.questionQCM = questionQCM;
        initComponents();
        madifierContenuQCM();
    }
    // Constructeur #2 (Question Image avec Erreur)
    public PanneauParcours(ImageErreur questionImg) {
        this.questionImg = questionImg;
        initComponents();
        madifierContenuImg();
    }
     // Constructeur #3 (Question Resultat execution)
    public PanneauParcours(ResultatExecution questionResExe) {
        this.questionResExe = questionResExe;
        initComponents();
        madifierContenuResExe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    /*private void initComponents() {

        
        lblTitre = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        setPreferredSize(new java.awt.Dimension(885, 455));
        setLayout(null);

        //jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 102, 102)));

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        lblTitre.setText("Titre ...");
        lblTitre.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
       // jPanel1.add(lblTitre);

        //add(jPanel1);
        //jPanel1.setBounds(120, 30, 650, 50);
    }// </editor-fold>    */                    

    
    // panneau Resultat d execution
    private void madifierContenuResExe() {
        lblTitre.setText(questionResExe.getTitre());
        txtArea = new JTextArea(questionResExe.getQuestion());
        txtArea.setMargin(new Insets(10,10,10,10));
        txtArea.setBounds(170, 110, 490, 210);
        txtArea.setFont(new Font("Tahoma", 0, 17));
        txtArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        txtArea.setEditable(false);
        add(txtArea);
        setBounds(0, 50, 885, 455);
    }
    
    // Panneau Image erreur
    private void madifierContenuImg() {
        lblTitre.setText(questionImg.getTitre());
        lblQuestion = new JLabel();
        lblQuestion.setBounds(115, 99, 650, 290);
        add(lblQuestion);
        // Afficher l'image de la question
        lblQuestion.setIcon(new ImageIcon(GestionImage.ajusterImage(
            new ImageIcon(getClass().getResource(questionImg.getlImage())).getImage(),lblQuestion.getWidth(),lblQuestion.getHeight())));
        setBounds(0, 50, 885, 455);
    }

    // Panneau QCM
    private void madifierContenuQCM() {

        lblTitre.setText(questionQCM.getTitre());
        lblQuestion = new JLabel();
        lblQuestion.setBackground(new java.awt.Color(51, 51, 255));
        lblQuestion.setFont(new java.awt.Font("Tahoma", 1, 17));
       // lblQuestion.setText((questionQCM.getLaQuestion().length() > 120) ? verifierLabel(questionQCM.getLaQuestion(), 120) : questionQCM.getLaQuestion());
        lblQuestion.setText("<html>"+questionQCM.getLaQuestion()+"</html>");
        add(lblQuestion);
        lblQuestion.setBounds(91, 91, 710, 75);
        int y = 95;
        tabChoix = new JLabel[questionQCM.getListeChoix().size()];

        passerSouris = new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseMoved(evt);
            }
        };
        sortirSouris = new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseExited(evt);
            }
        };
        for (int i = 0; i < questionQCM.getListeChoix().size(); i++) {
            //tabChoix[i] = new JCheckBox((question.getChoix(i).length() > 100) ? verifierLabel(question.getChoix(i), 100) : question.getChoix(i));
            tabChoix[i] = new JLabel("<html>" + questionQCM.getChoix(i) + "</html>");
            tabChoix[i].setFont(new java.awt.Font("Tahoma", 0, 17));
            tabChoix[i].addMouseMotionListener(passerSouris);
            tabChoix[i].addMouseListener(sortirSouris);
            tabChoix[i].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            tabChoix[i].setBackground(new java.awt.Color(219, 219, 219));
            tabChoix[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/liste_puce.jpg")));
            tabChoix[i].setBounds(73, (y + 65), 750, 50);
            add(tabChoix[i]);
            y += 53;
        }
        setBounds(0, 50, 885, 455);
    }

    //verifier la longueur de la question
    private String verifierLabel(String laQuestion, int tailleMax) {
        if (" ".equals(laQuestion.substring(tailleMax - 1, tailleMax))) {
            return ("<html>" + laQuestion.substring(0, tailleMax - 1) + "<br>" + laQuestion.substring(tailleMax, laQuestion.length()) + "</html>");
        } else if (" ".equals(laQuestion.substring(tailleMax, tailleMax + 1))) {
            return ("<html>" + laQuestion.substring(0, tailleMax) + "<br>" + laQuestion.substring(tailleMax + 1, laQuestion.length()) + "+</html>");
        } else {
            String resultat = "";
            String[] tab = laQuestion.substring(0, tailleMax).split(" ", 0);
            for (int i = 0; i < tab.length - 1; i++) {
                resultat = resultat + tab[i] + " ";
            }
            resultat = "<html>" + resultat + "<br>" + tab[tab.length - 1] + laQuestion.substring(tailleMax, laQuestion.length()) + "</html>";
            return resultat;
        }
    }

    private void jCheckBox1MouseMoved(java.awt.event.MouseEvent evt) {
        int i = 0;
        while (evt.getSource() != tabChoix[i]) {
            i++;
        }
        tabChoix[i].setBackground(new java.awt.Color(153, 153, 153));
    }

    private void jCheckBox1MouseExited(java.awt.event.MouseEvent evt) {
        int i = 0;
        while (evt.getSource() != tabChoix[i]) {
            i++;
        }
        tabChoix[i].setBackground(new java.awt.Color(219, 219, 219));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitre = new javax.swing.JPanel();
        lblTitre = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setLayout(null);

        pnlTitre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTitre.setLayout(null);

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        lblTitre.setText("Titre ...");
        lblTitre.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlTitre.add(lblTitre);
        lblTitre.setBounds(60, 0, 570, 50);

        add(pnlTitre);
        pnlTitre.setBounds(120, 30, 650, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPanel pnlTitre;
    // End of variables declaration//GEN-END:variables
}
