/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import io.ManipFichier;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modele.ListeProfils;
import modele.Profil;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauResultat extends javax.swing.JPanel {

    /**
     * Creates new form PanneauResultat
     */
    private Profil monProfil;
    private ListeProfils maListeProfils;
    private boolean enregistre;
    private int typeQuestShoisies;
    private JLabel[] lblTypes;
    private final String[] typeQuestion = {"Choisir la ou les bonnes réponses",
        "Trouver l'erreur dans ce code", "Trouver le resultat d'execution de ce code"};

    public PanneauResultat(Profil monProfil, ListeProfils maListeProfils, int typeQuestShoisies) {
        this.monProfil = monProfil;
        this.maListeProfils = maListeProfils;
        this.typeQuestShoisies = typeQuestShoisies;
        initComponents();
        mettreAjourContenue(monProfil);
    }

    private void mettreAjourContenue(Profil monProfil1) {
        lblUtilisateur.setText(monProfil1.getUtilisateur());
        lblNombreQuestions.setText(String.valueOf(monProfil1.getNotes().length));
        ArrayList<String> types = new ArrayList<>();
        if ((typeQuestShoisies) == 1 || (typeQuestShoisies) == 3 || (typeQuestShoisies) == 5 || (typeQuestShoisies) == 7)
            types.add(typeQuestion[0]);
        if ((typeQuestShoisies) == 2 || (typeQuestShoisies) == 3 || (typeQuestShoisies) == 6 || (typeQuestShoisies) == 7)
            types.add(typeQuestion[1]);
        if (typeQuestShoisies >= 4)
            types.add(typeQuestion[2]);
        lblTypes = new JLabel[types.size()];
        System.out.println("types.size() --->"+types.size());
        for (int i = 0; i < types.size(); i++) {
            lblTypes[i] = new JLabel("*"+types.get(i));
            lblTypes[i].setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
            pnl1.add(lblTypes[i]);
            lblTypes[i].setBounds(260, 100+(i*30), 520, 21);
        }

        if (monProfil1.getDuree() < 60) {
            lblDuree.setText(String.valueOf(monProfil1.getDuree()) + " secondes");
        } else {
            lblDuree.setText(String.valueOf(monProfil1.getDuree() / 60) + " minutes, " + String.valueOf(monProfil1.getDuree() % 60) + " secondes");
        }
        int cpt = 0;
        for (int i = 0; i < monProfil1.getNotes().length; i++) {
            if (monProfil1.getNotes()[i]) {
                cpt++;
            }
        }
        lblBonnesReponses.setText(String.valueOf(cpt));
        progressBarNote.setValue(monProfil1.calculerNote());
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed();
            }
        });
        setBounds(50, 30, 885, 495);
    }

    // vérifier si le profil est a été enregistré ou non
    public boolean isEnregistre() {
        return enregistre;
    }

    // Enregistrer le profil
    public void btnEnregistrerActionPerformed() {
        maListeProfils.ajouterProfil(monProfil);
        ManipFichier.ecrireFichier("Fichiers\\data_profils.txt", maListeProfils.toString());
        btnEnregistrer.setEnabled(false);
        JOptionPane.showMessageDialog(null, monProfil.getUtilisateur() + ", Votre resultat a été bien enregistré.",
                "Enregistrement de profil avec succès", JOptionPane.INFORMATION_MESSAGE);
        enregistre = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHaut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl1 = new javax.swing.JPanel();
        lblUtilisateur = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreQuestions = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDuree = new javax.swing.JLabel();
        btnEnregistrer = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblBonnesReponses = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        progressBarNote = new javax.swing.JProgressBar();
        pnl3 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(885, 495));
        setLayout(null);

        pnlHaut.setBackground(new java.awt.Color(0, 102, 102));
        pnlHaut.setPreferredSize(new java.awt.Dimension(885, 57));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Le resultat obtenu");

        javax.swing.GroupLayout pnlHautLayout = new javax.swing.GroupLayout(pnlHaut);
        pnlHaut.setLayout(pnlHautLayout);
        pnlHautLayout.setHorizontalGroup(
            pnlHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHautLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        pnlHautLayout.setVerticalGroup(
            pnlHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHautLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlHaut);
        pnlHaut.setBounds(0, 0, 890, 50);

        pnl1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, new java.awt.Color(0, 102, 102)));
        pnl1.setPreferredSize(new java.awt.Dimension(885, 240));
        pnl1.setLayout(null);

        lblUtilisateur.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        lblUtilisateur.setText("Utilisateur,");
        pnl1.add(lblUtilisateur);
        lblUtilisateur.setBounds(41, 30, 160, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setText("Vous avez passer un test de ");
        pnl1.add(jLabel3);
        jLabel3.setBounds(50, 69, 189, 18);

        lblNombreQuestions.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        lblNombreQuestions.setText("15");
        pnl1.add(lblNombreQuestions);
        lblNombreQuestions.setBounds(241, 66, 20, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel5.setText("questions :");
        pnl1.add(jLabel5);
        jLabel5.setBounds(271, 69, 71, 18);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel9.setText("Dans une duree de :");
        pnl1.add(jLabel9);
        jLabel9.setBounds(50, 196, 132, 18);

        lblDuree.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        lblDuree.setText("1 minute");
        pnl1.add(lblDuree);
        lblDuree.setBounds(200, 193, 190, 22);

        btnEnregistrer.setBackground(new java.awt.Color(0, 102, 102));
        btnEnregistrer.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btnEnregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database-add-icon.png"))); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        pnl1.add(btnEnregistrer);
        btnEnregistrer.setBounds(697, 30, 160, 40);

        add(pnl1);
        pnl1.setBounds(0, 50, 885, 240);

        pnl2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(0, 102, 102)));
        pnl2.setPreferredSize(new java.awt.Dimension(885, 80));
        pnl2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel11.setText("Vous avez obtenu");
        pnl2.add(jLabel11);
        jLabel11.setBounds(33, 32, 116, 18);

        lblBonnesReponses.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        lblBonnesReponses.setText("10");
        pnl2.add(lblBonnesReponses);
        lblBonnesReponses.setBounds(159, 29, 20, 22);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel13.setText("bonnes reponses");
        pnl2.add(jLabel13);
        jLabel13.setBounds(189, 32, 113, 18);

        progressBarNote.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        progressBarNote.setForeground(new java.awt.Color(0, 102, 102));
        progressBarNote.setValue(66);
        progressBarNote.setStringPainted(true);
        pnl2.add(progressBarNote);
        progressBarNote.setBounds(385, 31, 434, 22);

        add(pnl2);
        pnl2.setBounds(0, 290, 885, 80);

        pnl3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        add(pnl3);
        pnl3.setBounds(0, 370, 885, 125);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBonnesReponses;
    private javax.swing.JLabel lblDuree;
    private javax.swing.JLabel lblNombreQuestions;
    private javax.swing.JLabel lblUtilisateur;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnlHaut;
    private javax.swing.JProgressBar progressBarNote;
    // End of variables declaration//GEN-END:variables
}
