/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.GestionImage;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauDebutQuiz extends javax.swing.JPanel {

    private String utilisateur;
    private int nombreQuestion;
    private int typeQuestion; //{1,2,4}
    private int minuterie = 2;
    private ResourceBundle monBundle;

    // Constructeurs
    public PanneauDebutQuiz(ResourceBundle monBundle) {
        this.monBundle = monBundle;
        initComponents();

        comboBoxNbrQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"10", "15","25"}));
        //comboBoxNbrQuestion.addItem("25");
        setBounds(215, 100, 750, 450);
        
     
    }
    
    // Getters 
    public String getUtilisateur() {
        utilisateur = ((txtUtilisateur.getText().equals("")) ? "Utilisateur" : txtUtilisateur.getText());
        return utilisateur;
    }

    public int getNombreQuestion() {
        nombreQuestion = Integer.parseInt(comboBoxNbrQuestion.getSelectedItem().toString());
        return nombreQuestion;
    }

    public int getTypeQuestion() {
        typeQuestion = 0;
        if (chckbxQCM.isSelected()) {
            typeQuestion += 1;
        }
        if (chckbxTrouverErreurs.isSelected()) {
            typeQuestion += 2;
        }
        if (chckbxTrouverResultat.isSelected()) {
            typeQuestion += 4;
        }
        return typeQuestion;
    }

    public int getMinuterie() {
        return minuterie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblUtilisateur = new javax.swing.JLabel();
        txtUtilisateur = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        pnl2 = new javax.swing.JPanel();
        comboBoxNbrQuestion = new javax.swing.JComboBox<>();
        lblMinutes = new javax.swing.JLabel();
        lblMinuterie = new javax.swing.JLabel();
        txtMinutes = new javax.swing.JTextField();
        pnl3 = new javax.swing.JPanel();
        chckbxQCM = new javax.swing.JCheckBox();
        chckbxTrouverErreurs = new javax.swing.JCheckBox();
        chckbxTrouverResultat = new javax.swing.JCheckBox();
        lblQCM = new javax.swing.JLabel();
        lblErreurs = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(770, 450));
        setLayout(null);

        pnl1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, monBundle.getString("LBLprenom"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15))); // NOI18N
        pnl1.setPreferredSize(new java.awt.Dimension(620, 75));
        pnl1.setLayout(null);

        lblUtilisateur.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().getResource("/images/user.png")).getImage(), 51, 51)));
        pnl1.add(lblUtilisateur);
        lblUtilisateur.setBounds(599, 21, 51, 51);

        txtUtilisateur.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtUtilisateur.setText(monBundle.getString("TxtUtilisateur"));
        txtUtilisateur.setFocusCycleRoot(true);
        txtUtilisateur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUtilisateurFocusGained(evt);
            }
        });
        pnl1.add(txtUtilisateur);
        txtUtilisateur.setBounds(55, 35, 175, 29);
        pnl1.add(jTextField3);
        jTextField3.setBounds(10, 20, 0, 0);

        add(pnl1);
        pnl1.setBounds(55, 35, 670, 80);

        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, monBundle.getString("LBLchoisir"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15))); // NOI18N
        pnl2.setPreferredSize(new java.awt.Dimension(620, 75));
        pnl2.setLayout(null);

        comboBoxNbrQuestion.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        comboBoxNbrQuestion.setName(""); // NOI18N
        comboBoxNbrQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNbrQuestionActionPerformed(evt);
            }
        });
        pnl2.add(comboBoxNbrQuestion);
        comboBoxNbrQuestion.setBounds(55, 35, 175, 29);
        comboBoxNbrQuestion.getAccessibleContext().setAccessibleName("");

        lblMinutes.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblMinutes.setText(monBundle.getString("LblDuree"));
        pnl2.add(lblMinutes);
        lblMinutes.setBounds(259, 31, 220, 29);

        lblMinuterie.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().getResource("/images/Document-scheduled-tasks-icon.png")).getImage(), 51, 51)));
        pnl2.add(lblMinuterie);
        lblMinuterie.setBounds(599, 21, 51, 51);

        txtMinutes.setEditable(false);
        txtMinutes.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtMinutes.setForeground(new java.awt.Color(255, 0, 0));
        txtMinutes.setText(String.valueOf(minuterie));
        pnl2.add(txtMinutes);
        txtMinutes.setBounds(480, 30, 40, 29);

        add(pnl2);
        pnl2.setBounds(55, 130, 670, 80);

        pnl3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, monBundle.getString("LBLtype")
            , javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
    pnl3.setLayout(null);

    chckbxQCM.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
    chckbxQCM.setSelected(true);
    chckbxQCM.setText(monBundle.getString("QCM"));
    chckbxQCM.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            chckbxActionPerformed(evt);
        }
    });
    pnl3.add(chckbxQCM);
    chckbxQCM.setBounds(55, 45, 280, 29);

    chckbxTrouverErreurs.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
    chckbxTrouverErreurs.setSelected(true);
    chckbxTrouverErreurs.setText(monBundle.getString("QuesErreur"));
    chckbxTrouverErreurs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            chckbxActionPerformed(evt);
        }
    });
    pnl3.add(chckbxTrouverErreurs);
    chckbxTrouverErreurs.setBounds(55, 95, 380, 29);

    chckbxTrouverResultat.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
    chckbxTrouverResultat.setSelected(true);
    chckbxTrouverResultat.setText(monBundle.getString("QuesResExe"));
    chckbxTrouverResultat.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            chckbxActionPerformed(evt);
        }
    });
    pnl3.add(chckbxTrouverResultat);
    chckbxTrouverResultat.setBounds(55, 145, 450, 29);

    lblQCM.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().getResource("/images/QCM-icon.png")).getImage(), 79, 79)));
    pnl3.add(lblQCM);
    lblQCM.setBounds(479, 25, 79, 79);

    lblErreurs.setIcon(new ImageIcon(GestionImage.ajusterImage(new ImageIcon(getClass().getResource("/images/erreurs_code_java.jpg")).getImage(), 79, 79)));
    pnl3.add(lblErreurs);
    lblErreurs.setBounds(575, 95, 79, 79);

    add(pnl3);
    pnl3.setBounds(55, 225, 670, 190);
    }// </editor-fold>//GEN-END:initComponents

    // Vérifier si au moins un type de question est choisi
    private void chckbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxActionPerformed
        if (!chckbxQCM.isSelected() && !chckbxTrouverErreurs.isSelected() && !chckbxTrouverResultat.isSelected()) {
            if (evt.getSource() == chckbxQCM) {
                chckbxQCM.setSelected(true);
            } else if (evt.getSource() == chckbxTrouverErreurs) {
                chckbxTrouverErreurs.setSelected(true);
            } else {
                chckbxTrouverResultat.setSelected(true);
            }
            JOptionPane.showMessageDialog(null, "Attention! Vous devez choisir au moins un type de question",
                    "Erreur selection", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chckbxActionPerformed

    // Choix de nombre de Question
    private void comboBoxNbrQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNbrQuestionActionPerformed
        switch (comboBoxNbrQuestion.getSelectedItem().toString()) {
            case "10":
                minuterie = 2;
                break;
            case "15":
                minuterie = 3;
                break;
            case "25":
                minuterie = 5;
                break;
            default:
        }
        txtMinutes.setText(String.valueOf(minuterie));
    }//GEN-LAST:event_comboBoxNbrQuestionActionPerformed

    // Vider zone de texte nom d'utilisateur
    private void txtUtilisateurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUtilisateurFocusGained
        txtUtilisateur.setText("");
    }//GEN-LAST:event_txtUtilisateurFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chckbxQCM;
    private javax.swing.JCheckBox chckbxTrouverErreurs;
    private javax.swing.JCheckBox chckbxTrouverResultat;
    private javax.swing.JComboBox<String> comboBoxNbrQuestion;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblErreurs;
    private javax.swing.JLabel lblMinuterie;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblQCM;
    private javax.swing.JLabel lblUtilisateur;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JTextField txtMinutes;
    private javax.swing.JTextField txtUtilisateur;
    // End of variables declaration//GEN-END:variables

}
