/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import modele.ListeQuestions;
import utils.GestionScenario;

/**
 *
 * @author Ferfar Imad Eddine
 */
public class PanneauParcoursPrincipal extends javax.swing.JPanel {

    private ListeQuestions listeQuestions;
    private PanneauParcours monPanneau;
    private int compteur = 0;

    public PanneauParcoursPrincipal(ListeQuestions listeQuestions) {
        this.listeQuestions = listeQuestions;
        initComponents();
        afficherQuestions(listeQuestions);
    }

    private void afficherQuestions(ListeQuestions listeQuestions) {
        int minCle = listeQuestions.minCle();
        //this.monPanneau = new PanneauParcours((QCM)listeQuestions.getQuestionN(minCle));
        this.monPanneau = GestionScenario.LancerPanneau(listeQuestions,listeQuestions.tableauCles()[compteur]);
        add(monPanneau);
        mettreAjourBoutonsEtNum();
        setBounds(50, 30, 885, 555);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBas = new javax.swing.JPanel();
        btnSuivant = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        lblNumero = new javax.swing.JLabel();
        pnlHaut = new javax.swing.JPanel();
        btnProchainType = new javax.swing.JButton();
        btnPresedentType = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setPreferredSize(new java.awt.Dimension(885, 555));
        setLayout(null);

        pnlBas.setBackground(new java.awt.Color(0, 153, 153));

        btnSuivant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Next-icon.png"))); // NOI18N
        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnPrecedent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Previous-icon.png"))); // NOI18N
        btnPrecedent.setText("Precedent");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        lblNumero.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNumero.setText("***");

        javax.swing.GroupLayout pnlBasLayout = new javax.swing.GroupLayout(pnlBas);
        pnlBas.setLayout(pnlBasLayout);
        pnlBasLayout.setHorizontalGroup(
            pnlBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnPrecedent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(btnSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnlBasLayout.setVerticalGroup(
            pnlBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrecedent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlBas);
        pnlBas.setBounds(0, 505, 885, 50);

        pnlHaut.setBackground(new java.awt.Color(255, 255, 255));
        pnlHaut.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        pnlHaut.setLayout(null);

        btnProchainType.setBackground(new java.awt.Color(255, 255, 255));
        btnProchainType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_globe_forward_to_end_588 - Copy.jpg"))); // NOI18N
        btnProchainType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProchainTypeActionPerformed(evt);
            }
        });
        pnlHaut.add(btnProchainType);
        btnProchainType.setBounds(755, 7, 35, 35);

        btnPresedentType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_globe_forward_to_end_588.jpg"))); // NOI18N
        btnPresedentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresedentTypeActionPerformed(evt);
            }
        });
        pnlHaut.add(btnPresedentType);
        btnPresedentType.setBounds(95, 7, 35, 35);

        lblType.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        lblType.setText(" << Questions a choix multiple >>");
        pnlHaut.add(lblType);
        lblType.setBounds(200, 10, 540, 30);

        add(pnlHaut);
        pnlHaut.setBounds(0, 0, 885, 50);
    }// </editor-fold>//GEN-END:initComponents

    // Bouton Suivant
    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        compteur++;
        chargerNouveauPanneau();
    }//GEN-LAST:event_btnSuivantActionPerformed

    //Bouton Precedent
    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        compteur--;
        chargerNouveauPanneau();
    }//GEN-LAST:event_btnPrecedentActionPerformed

    // charger un nouveau panneau
    private void chargerNouveauPanneau(){
        mettreAjourBoutonsEtNum();
        remove(monPanneau);
        monPanneau = GestionScenario.LancerPanneau(listeQuestions,listeQuestions.tableauCles()[compteur]);
        add(monPanneau);
        repaint();
    }
    
    //type suivant
    private void btnProchainTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProchainTypeActionPerformed
        String message = listeQuestions.getQuestionN(listeQuestions.tableauCles()[compteur]).getTitre();
        while(listeQuestions.getQuestionN(listeQuestions.tableauCles()[compteur]).getTitre().equals(message)){
            compteur++;
            mettreAjourBoutonsEtNum();
        }
        mettreAjourBoutonsEtNum();
        remove(monPanneau);
        monPanneau = GestionScenario.LancerPanneau(listeQuestions,listeQuestions.tableauCles()[compteur]);
        add(monPanneau);
        repaint(); 
    }//GEN-LAST:event_btnProchainTypeActionPerformed

    // type precedent
    private void btnPresedentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresedentTypeActionPerformed
       String message = listeQuestions.getQuestionN(listeQuestions.tableauCles()[compteur]).getTitre();
        while(listeQuestions.getQuestionN(listeQuestions.tableauCles()[compteur]).getTitre().equals(message)){
            compteur--;
            mettreAjourBoutonsEtNum();
        }
        mettreAjourBoutonsEtNum();
        remove(monPanneau);
        monPanneau = GestionScenario.LancerPanneau(listeQuestions,listeQuestions.tableauCles()[compteur]);
        add(monPanneau);
        repaint(); 
    }//GEN-LAST:event_btnPresedentTypeActionPerformed
    
    //Méthode pour mettre a jour les boutons et le numéro 
    private void mettreAjourBoutonsEtNum() {
        if (compteur > listeQuestions.getSize()-1)
            compteur = 0;
        else if (compteur <0 )
            compteur = listeQuestions.getSize()-1;
        lblNumero.setText("(Question " + (compteur + 1) + "/" + listeQuestions.getSize() + ")");
        lblType.setText("<< "+listeQuestions.getQuestionN(listeQuestions.tableauCles()[compteur]).getTitre()+" >>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnPresedentType;
    private javax.swing.JButton btnProchainType;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnlBas;
    private javax.swing.JPanel pnlHaut;
    // End of variables declaration//GEN-END:variables
}
